version: "3.9"

services:
#  medicalert:
#    build:
#      context: ../../../Medicalert
#      dockerfile: ../.devops/docker/develop/Dockerfile
#    volumes:
#      - ./data:/Medicalert/data
#    networks:
#      - java-medicalert
#    depends_on:
#      - db-postgres

  db-postgres:
    image: postgres:13
    container_name: medicalert-postgres
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "homestead"
      POSTGRES_DB: "medicalert"
    volumes: 
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - java-medicalert

networks:
  java-medicalert:
    driver: bridge

